package:
  name: onesheet
  version: "0.1.5.2b1"

source:
  fn: OneSheet-0.1.5.1.tar.gz
  url: https://pypi.python.org/packages/source/O/OneSheet/OneSheet-0.1.5.1.tar.gz
  md5: 30d29c383a13d8d6d904a46e42839cc0
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 2
  string: b

  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - onesheet = onesheet:main
    #
    # Would create an entry point called onesheet that calls onesheet.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - onesheet

  commands:
    - ffprobe -version

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/henryborchers/OneSheet
  license: GNU General Public License v3 (GPLv3)
  summary: 'Easily access metadata for image, video, sound, and document file.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
